apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-celery-flower-deployment
  namespace: default
  labels:
    app: django-celery-flower
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: django-celery-flower
  template:
    metadata:
      labels:
        app: django-celery-flower
    spec:
      terminationGracePeriodSeconds: 3800
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
        - name: django-celery-flower-image
          image: mher/flower:latest
          command: [ "/bin/sh","-c" ]
          args: [celery flower  -A core ]
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "100M"
            limits:
              cpu: "150m"
              memory: "200M"
          ports:
            - containerPort: 5555
          readinessProbe:
            httpGet:
              path: /
              port: 5555
            initialDelaySeconds: 30
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /
              port: 5555
            initialDelaySeconds: 15
            periodSeconds: 120
          env:
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: djangosecrets
                  key: database_name
                  optional: false

            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: djangosecrets
                  key: database_user
                  optional: false

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: djangosecrets
                  key: database_password
                  optional: false

            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: djangosecrets
                  key: database_host
                  optional: false

            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: djangosecrets
                  key: database_port
                  optional: false
                  
            - name: ALLOWED_HOST
              valueFrom:
                secretKeyRef:
                  name: djangosecrets
                  key: allowed_host
                  optional: false

            - name: CELERY_BROKER_URL
              value: redis://redis:6379
            - name: CELERY_RESULT_URL
              value: redis://redis:6379

            - name: REDIS_HOST
              value: redis

---
apiVersion: v1
kind: Service
metadata:
  name: django-celery-flower-load-balancer
spec:
  type: NodePort
  selector:
    app: django-celery-flower
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
      nodePort: 31001



